data:
  scenario: legacy
  overrides:
    sources:
      assignment.students:
        path: /share/data/school_choice/Data/Cleaned/r1_filter_student_without_specialprogs_2324.csv
        classification: restricted
      assignment.programs:
        path: /share/data/school_choice/Data/Cleaned/programs_without_specialprogs_2324.csv
        classification: internal
      assignment.schools:
        path: /share/data/school_choice/Data/Cleaned/schools_rehauled_withMissionBay_2324.csv
        classification: internal
      assignment.estimate:
        path: /share/data/school_choice/simulation-files/choice-model/estimates_2324_exp8_0514.csv
        classification: restricted
      assignment.school_coordinates:
        path: /share/data/school_choice/Data/Cleaned/schools_rehauled_withMissionBay_2324.csv
        classification: internal
      assignment.zones:
        10zone:
          path: /share/data/school_choice/simulation-files/zones/10-zone-11_BG.csv
          classification: public
        13zone:
          path: /share/data/school_choice/simulation-files/zones/13-zone-7_BG.csv
          classification: public
        18zone_1:
          path: /share/data/school_choice/simulation-files/zones/18-zone-1_1_BG.csv
          classification: public
        18zone_2:
          path: /share/data/school_choice/simulation-files/zones/18-zone-1_2_BG.csv
          classification: public
        59zone:
          path: /share/data/school_choice/simulation-files/zones/59-zone-1_B.csv
          classification: public
        6zone-1:
          path: /share/data/school_choice/simulation-files/zones/6-zone-1_BG.csv
          classification: public
        6zone-9_1:
          path: /share/data/school_choice/simulation-files/zones/6-zone-9_1_BG.csv
          classification: public
        6zone-9_2:
          path: /share/data/school_choice/simulation-files/zones/6-zone-9_2_BG.csv
          classification: public
        Con1:
          path: /share/data/school_choice/simulation-files/zones/concept1zones.csv
          classification: public
        Zones_6_FRL_Dev_0.10_Objective_1430.0_6-zone-3:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_6_FRL_Dev_0.10_Objective_1430.0_6-zone-3.csv
          classification: public
        Zones_10_FRL_Dev_0.15_Objective_2150.0_10-zone-6:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_10_FRL_Dev_0.15_Objective_2150.0_10-zone-6.csv
          classification: public
        Zones_10_FRL_Dev_0.15_Objective_2250.0_10-zone-6:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_10_FRL_Dev_0.15_Objective_2250.0_10-zone-6.csv
          classification: public
        Zones_10_FRL_Dev_0.15_Objective_2270.0_10-zone-3:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_10_FRL_Dev_0.15_Objective_2270.0_10-zone-3.csv
          classification: public
        Zones_10_FRL_Dev_0.20_Objective_1960.0_10-zone:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_10_FRL_Dev_0.20_Objective_1960.0_10-zone.csv
          classification: public
        Zones_13_FRL_Dev_0.25_Objective_2500.0_13-zone-2:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_13_FRL_Dev_0.25_Objective_2500.0_13-zone-2.csv
          classification: public
        Zones_18_FRL_Dev_0.30_Objective_2820.0_18-zone-1:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_18_FRL_Dev_0.30_Objective_2820.0_18-zone-1.csv
          classification: public
        Zones_18_FRL_Dev_0.30_Objective_2830.0_18-zone-6:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_18_FRL_Dev_0.30_Objective_2830.0_18-zone-6.csv
          classification: public
        Zones_6_FRL_Dev_0.10_Objective_1500.0_6-zone:
          path: <STUDENT_ASSIGNMENT_PATH>/data/zones/Zones_6_FRL_Dev_0.10_Objective_1500.0_6-zone.csv
          classification: public
      assignment.citywide_zones:
        18zone_1_2-BG-0point3miles:
          path: /share/data/school_choice/simulation-files/zones/18-zone_1_2-additiona-0point3miles.txt
          classification: public
    filters:
      assignment:
        year: "2324"
        grades: [KG]
        student_population: applicant
        rounds:
        - 1
        special_programs: exclude_any_special
        capacity_profile: status_quo
        include_mission_bay: true
iterations:
  end: 5
  start: 0
paths:
  assignment-folder: <STUDENT_ASSIGNMENT_PATH>/local-data/local-runs/augmentation_experiments/baseline/
r1-only: true
random-seed: 2023
rounds-merged-options:
- 0
save-assignment: true
subconfigs:
- small_zones+no_reserves
- small_zones+reserves
- small_zones+reserves_05frl
- small_zones+reserves_06frl
- medium_zones+no_reserves
- medium_zones+reserves
- medium_zones+reserves_05frl
- medium_zones+reserves_06frl
- distance_05_1_2+reserves
- distance_05_1_2+reserves_05frl
- distance_05_1_2+reserves_06frl
- distance_05_3
- distance_05_3+reserves
- distance_05_3+reserves_05frl
- distance_05_3+reserves_06frl
- distance_05_1_3
- distance_05_1_3+reserves
- distance_05_1_3+reserves_05frl
- distance_05_1_3+reserves_06frl
- status_quo
- status_quo+guardrails
- status_quo+reserves
- status_quo+reserves_05frl
- status_quo+reserves_06frl
- generated/Zones_13_FRL_Dev_0.25_Objective_2500.0_13-zone-2+no_reserves
- generated/Zones_13_FRL_Dev_0.25_Objective_2500.0_13-zone-2+reserves
- generated/Zones_13_FRL_Dev_0.25_Objective_2500.0_13-zone-2+reserves_05frl
- generated/Zones_13_FRL_Dev_0.25_Objective_2500.0_13-zone-2+reserves_06frl
- generated/Zones_10_FRL_Dev_0.15_Objective_2250.0_10-zone-6+no_reserves
- generated/Zones_10_FRL_Dev_0.15_Objective_2250.0_10-zone-6+reserves
- generated/Zones_10_FRL_Dev_0.15_Objective_2250.0_10-zone-6+reserves_05frl
- generated/Zones_10_FRL_Dev_0.15_Objective_2250.0_10-zone-6+reserves_06frl
- generated/Zones_6_FRL_Dev_0.10_Objective_1430.0_6-zone-3+no_reserves
- generated/Zones_6_FRL_Dev_0.10_Objective_1430.0_6-zone-3+reserves
- generated/Zones_6_FRL_Dev_0.10_Objective_1430.0_6-zone-3+reserves_05frl
- generated/Zones_6_FRL_Dev_0.10_Objective_1430.0_6-zone-3+reserves_06frl
utility-model:
  designate-lp-for-all: false
  enable: false
  list-length: 0.8*round(real_length)
  save-path: <STUDENT_ASSIGNMENT_PATH>/local-data/local-runs/augmentation_experiments/utility_matrix.csv
list-augmentation:
  enable: true
  targeting-method: ctip_x_ethnicity
  short-list-threshold: 3
  oversubscribed-method: first_choice_per_seat
  oversubscribed-ratio-threshold: 1.5
  oversubscribed-fixed-schools:
  - 420
  - 478
  - 497
  - 521
  - 722
  - 735
  - 867
  max-augmented-programs: 1
