BASE_CONFIG_NAME = "base_config.yaml"
LOCAL_PATH_CONFIG_NAME = "local_path_config.yaml"
CLUSTER_PATH_CONFIG_NAME = "cluster_path_config.yaml"
CONFIG_SCHEMA_NAME = "config_schema.yaml"
USER_CONFIG_SUFFIX = ".config.yaml"
