from enum import Enum

LANGUAGE_PATHWAY_PRIORITIES = {
    "NS": ["NS", "SB", "SN"],
    "SB": ["SB", "SN", "NS"],
    "SN": ["SN", "SB", "NS"],
    "SE": ["SN", "SE"],
    "NC": ["NC", "CB", "CN"],
    "CB": ["CB", "CN", "NC"],
    "CN": ["CN", "CB", "NC"],
    "CE": ["CN", "CE"],
    "JN": ["JN"],
    "JE": ["JE", "JN"],
    "JB": ["JB"],
    "MN": ["MN"],
    "ME": ["MN", "ME"],
    "KN": ["KN"],
    "KE": ["KN", "KE"],
    "NX": ["NX"],
}

LANGUAGE_PATHWAYS = {
    "NS",
    "SB",
    "SN",
    "SB",
    "SN",
    "NS",
    "SN",
    "SB",
    "NS",
    "SN",
    "SE",
    "NC",
    "CB",
    "CN",
    "CB",
    "CN",
    "NC",
    "CN",
    "CB",
    "NC",
    "CN",
    "CE",
    "JN",
    "JE",
    "JN",
    "JB",
    "MN",
    "MN",
    "ME",
    "KN",
    "KN",
    "KE",
    "NX",
}

K8S = [618, 449, 676, 479, 760, 796, 493, 485]

CW2AA = {
    449: 497,
    476: 872,
    485: 478,
    796: 478,
    479: 848,
    493: 729,
    509: 718,
    537: 575,
    724: 575,
    618: 603,
    676: 782,
    760: 680,
    714: 723,
    814: 823,
}

SPECIAL_PROGRAMS = {"AF", "DA", "DT", "ED", "MM", "MS", "SA", "TC", "AO"}

ZONE_COLORS = {
    0: "red",
    664: "red",
    1: "midnightblue",
    521: "midnightblue",
    2: "green",
    420: "green",
    3: "orange",
    435: "orange",
    4: "purple",
    497: "purple",
    5: "brown",
    453: "brown",
    6: "pink",
    456: "pink",
    7: "cyan",
    848: "cyan",
    8: "magenta",
    593: "magenta",
    9: "olive",
    481: "olive",
    10: "teal",
    488: "teal",
    11: "lime",
    790: "lime",
    12: "darkolivegreen",
    490: "darkolivegreen",
    13: "crimson",
    729: "crimson",
    14: "darkgreen",
    505: "darkgreen",
    15: "gold",
    816: "gold",
    16: "indigo",
    513: "indigo",
    17: "salmon",
    549: "salmon",
    18: "yellowgreen",
    750: "yellowgreen",
    19: "maroon",
    525: "maroon",
    20: "violet",
    575: "violet",
    21: "tan",
    539: "tan",
    22: "darkblue",
    999: "darkblue",
    23: "darkred",
    562: "darkred",
    24: "darkorange",
    569: "darkorange",
    25: "turquoise",
    589: "turquoise",
    26: "dodgerblue",
    862: "dodgerblue",
    27: "mediumvioletred",
    614: "mediumvioletred",
    28: "orchid",
    625: "orchid",
    29: "peru",
    638: "peru",
    30: "slateblue",
    644: "slateblue",
    31: "tomato",
    650: "tomato",
    32: "aquamarine",
    656: "aquamarine",
    33: "steelblue",
    413: "steelblue",
    34: "cornflowerblue",
    718: "cornflowerblue",
    35: "darkseagreen",
    670: "darkseagreen",
    36: "cadetblue",
    782: "cadetblue",
    37: "sandybrown",
    801: "sandybrown",
    38: "mediumorchid",
    691: "mediumorchid",
    39: "palevioletred",
    834: "palevioletred",
    40: "mediumpurple",
    723: "mediumpurple",
    41: "coral",
    722: "coral",
    42: "darkcyan",
    735: "darkcyan",
    43: "firebrick",
    746: "firebrick",
    44: "forestgreen",
    872: "forestgreen",
    45: "limegreen",
    507: "limegreen",
    46: "royalblue",
    786: "royalblue",
    47: "darkorchid",
    820: "darkorchid",
    48: "hotpink",
    830: "hotpink",
    49: "indianred",
    838: "indianred",
    50: "navy",
    544: "navy",
    51: "dimgray",
    823: "dimgray",
    52: "lightseagreen",
    680: "lightseagreen",
    53: "sienna",
    842: "sienna",
    54: "mediumseagreen",
    859: "mediumseagreen",
    55: "darkgoldenrod",
    478: "darkgoldenrod",
    56: "deepskyblue",
    867: "deepskyblue",
    57: "rosybrown",
    876: "rosybrown",
    58: "darkkhaki",
    603: "darkkhaki",
}


class PrefLength(Enum):
    """The preference length policy setting.
    If you want different combinations of the policy,
    ex. you want real length time 2
    you can input config as realLength$x2$
    or if you want real length plus 3
    you can input config as realLength$+3$
    of if want absolute preference length of 7
    you can input policy config as absLength$7$.
    """

    REAL_LENGTH = "realLength"
    LENGTH_BY_ETHN = "lengthByEthn"
    ABS_LENGTH = "absLength"

    @classmethod
    def list(cls):
        return list(map(lambda c: c.value, cls))
