
# changing levers
#centroids_type: '4-zone-rec-4'
centroids_type: '6-zone-2'
#centroids_type: '8-zone-25'
#centroids_type: '10-zone-3'
#centroids_type: '18-zone-7'
#centroids_type: '57-zone-1'

frl_dev: 0.3
racial_dev: 0.3

# fixed levers
#boundary_threshold: .05
shortage: .2 # this is in percentage
overage: 0.8 # this is in percentage
all_cap_shortage: .inf # this is in percentage
max_distance: 4 # best valid value for 59 zines: 1.272
population_dev: .inf


years: [14, 15, 16, 17, 18, 21, 22]
population_type: "GE"
drop_optout: True
#capacity_scenario: "Closure" # A
capacity_scenario: "A"
new_schools: True
include_k8: False
# 'Block', 'BlockGroup' or 'attendance_area'
level: "BlockGroup"
start_level: "attendance_area"
end_level: "Block"

solve_time_limit: 300 # seconds
# mip, cp_int, cp_bool
optimizer: 'cp_bool'
# optimize with choice
optimize_with_choice: True
# simulate choice
simulate_choice: True

#capacity_vicinity: 0.005
#fixed_vicinity: 0.12

# move_SpEd: False

# unused metrics
# balance: 1000
# aalpi_dev: 0.15
# lbscqlty: 0.75
# HOCidx1_dev: 0.2

