
# changing levers
#centroids_type: '6-zone-2'
#centroids_type: '7-zone-14'
centroids_type: '8-zone-25'
#centroids_type: '10-zone-3'
#centroids_type: '13-zone-6'
#centroids_type: '18-zone-7'
#centroids_type: '57-zone-1'
#centroids_type: '59-zone'

frl_dev: 0.3
racial_dev: 0.3
is_local: False

# fixed levers
#boundary_threshold: .05
shortage: .2 # this is in percentage
overage: 0.8 # this is in percentage
all_cap_shortage: .inf # this is in percentage
max_distance: 5 # best valid value for 59 zines: 1.272
population_dev: .inf


years: [14, 15, 16, 17, 18, 21, 22]
population_type: "GE"
drop_optout: True
#capacity_scenario: "Closure" # A
capacity_scenario: "A"
new_schools: True
include_k8: False
# 'Block', 'BlockGroup' or 'attendance_area'
# Block_0, Block_1, Block_2, Block_3
level: "Block_1"
recursive_levels: ['Block_3', 'Block_2', 'Block_1', 'Block_0']
relative_gap_limits: [0.15, 0.15, 0.15, 0.1]

relative_gap_limit: 0.15
#log_folder: '.'
solve_time_limit: 45 # seconds
random_seed: 42
# mip, cp_int, cp_bool
optimizer: 'cp_int'
use_hints: True

# optimize with choice
optimize_with_choice: True
# simulate choice
simulate_choice: True

#capacity_vicinity: 0.005
#fixed_vicinity: 0.12

# move_SpEd: False

# unused metrics
# balance: 1000
# aalpi_dev: 0.15
# lbscqlty: 0.75
# HOCidx1_dev: 0.2

