
# changing levers
#centroids_type: '9-zone-west'
centroids_type: '6-zone-2'

frl_dev: 1
racial_dev: 1

# fixed levers
boundary_threshold: .05
shortage: 0.3 # this is in percentage
overage: 0.5 # this is in percentage
all_cap_shortage: .inf # this is in percentage
max_distance: .inf # best valid value for 59 zines: 1.272
population_dev: .inf
path: "/Users/mobin/SFUSD/Visualization_Tool_Data/AA_Zones/"


years: [14, 15, 16, 17, 18, 21, 22]
population_type: "GE"
drop_optout: True
capacity_scenario: "A"
new_schools: True
include_k8: False
# 'Block', 'BlockGroup' or 'attendance_area'
level: "attendance_area"

#capacity_vicinity: 0.005
#fixed_vicinity: 0.12

# move_SpEd: False

# unused metrics
# balance: 1000
# aalpi_dev: 0.15
# lbscqlty: 0.75
# HOCidx1_dev: 0.2

