
# changing levers
centroids_type: '20-zone-1'
frl_dev: 1
racial_dev: 1
include_k8: False

# fixed levers
boundary_threshold: .05
shortage: 0.3 # this is in percentage
overage: 0.3 # this is in percentage
all_cap_shortage: -1 # this is in percentage
population_type: "All"
max_distance: 1.28 # best valid value for 59 zines: 1.272
population_dev: -1
path: "/Users/mobin/SFUSD/Visualization_Tool_Data/"


#capacity_vicinity: 0.005
#fixed_vicinity: 0.12

# move_SpEd: False

# unused metrics
# balance: 1000
# aalpi_dev: 0.15
# lbscqlty: 0.75
# HOCidx1_dev: 0.2

