data:
  scenario: legacy
  overrides:
    sources:
      assignment.students:
        path: <STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_2223_filtered.csv
        classification: restricted
      assignment.programs:
        path: <STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_2223.csv
        classification: internal
      assignment.schools:
        path: /share/data/school_choice/Data/Cleaned/schools_rehauled_2223.csv
        classification: internal
      assignment.estimate:
        path: <SFUSD_CHOICE_PATH>/local_outputs/models/selected_2223_k1_prog_gesplit/estimates_2223.csv
        classification: restricted
      assignment.school_coordinates:
        path: /share/data/school_choice/Data/Cleaned/schools_rehauled_2223.csv
        classification: internal
      assignment.zones:
        10zone:
          path: /share/data/school_choice/simulation-files/zones/10-zone-11_BG.csv
          classification: public
        13zone:
          path: /share/data/school_choice/simulation-files/zones/13-zone-7_BG.csv
          classification: public
        18zone_1:
          path: /share/data/school_choice/simulation-files/zones/18-zone-1_1_BG.csv
          classification: public
        18zone_2:
          path: /share/data/school_choice/simulation-files/zones/18-zone-1_2_BG.csv
          classification: public
        59zone:
          path: /share/data/school_choice/simulation-files/zones/59-zone-1_B.csv
          classification: public
        6zone-1:
          path: /share/data/school_choice/simulation-files/zones/6-zone-1_BG.csv
          classification: public
        6zone-9_1:
          path: /share/data/school_choice/simulation-files/zones/6-zone-9_1_BG.csv
          classification: public
        6zone-9_2:
          path: /share/data/school_choice/simulation-files/zones/6-zone-9_2_BG.csv
          classification: public
        Con1:
          path: /share/data/school_choice/simulation-files/zones/concept1zones.csv
          classification: public
      assignment.citywide_zones:
        18zone_1_2-BG-0point3miles:
          path: /share/data/school_choice/simulation-files/zones/18-zone_1_2-additiona-0point3miles.txt
          classification: public
    filters:
      assignment:
        year: "2324"
        grades: [KG]
        student_population: applicant
        rounds:
        - 1
        special_programs: include
        capacity_profile: default
        include_mission_bay: false
iterations:
  end: 25
  start: 0
paths:
  assignment-folder: <STUDENT_ASSIGNMENT_PATH>/local-data/counterfactual_runs/baseline/selected_2223_k1_prog_gesplit/2223/
r1-only: true
random-seed: 2023
rounds-merged-options:
- 0
save-assignment: true
subconfigs:
- status_quo
utility-model:
  designate-lp-for-all: false
  enable: true
  list-length: 0.8*round(real_length)
  save-path: <STUDENT_ASSIGNMENT_PATH>/local-data/counterfactual_runs/baseline/selected_2223_k1_prog_gesplit/2223/utility_matrix.csv
