# Policy config for distance_05_1_2+reserves
assignment-algorithm: DA
ctip-options:
- 1

restrict-zone: false
guard-rails: 0
reserve-settings: {
  "column": "median_hh_income", 
  "thresholds": [95292], 
  "lower_disadvantaged": True",  
  "reserve_fraction": [0.57, 0.43]
  }
non_designation_boost: 128
soft_reserve_boost: 64

policies:
- Con1

priority-weights:
  ctip: 8
  sibling: 16
  distance: 4
  zone: 0
  language-programs:
    lp-sibling: 16
    lp: 8
    sibling: 4
    ctip: 2

distance-priority:
  # If to define the size (mile) of steps. Default to this option with 1 mile.
  # step-size: 1
  # If to use manual thresholds as steps for distance priorities.
  thresholds: [0.5, 1,2]
  # If to use continuous function on distance priorities. Currently only support
  # 1 / distance^2 (1_over_x_sqaure) or exact distance (x)
  # continuous: 1_over_x_sqaure
  #continuous: x
  
sibling-access: true
designate: true
zone-building-blocks: 'attendance_area'
ties-options:
- MTB
