assignment-algorithm: DA
ctip-options:
- 1
- 0

restrict-zone: true
guard-rails: -1


#"citywide_only": True}
#{"column": "median_hh_income", "thresholds": [95292], "lower_disadvantaged": True, "citywide_only": True}
#{"column": "median_hh_income", "thresholds": [95292], "lower_disadvantaged": True, "reserve_fraction": [0.57, 0.43], "citywide_only": True}
#{"column": "median_hh_income", "thresholds": [95292], "lower_disadvantaged": True, "reserve_fraction": [0.57, 0.43], "citywide_only": True}
#{"column": "median_hh_income", "thresholds": [95292], "lower_disadvantaged": True, "citywide_only": True}

policies:
- 18zone_2


priority-weights:
  ctip: 8
  zone: 4
  #These should have 
  language-programs:
    lp: 8
    ctip: 2


sibling-access: false
zone-building-blocks: block_group
designate: true
ties-options:
- MTB_REAL
