assignment-algorithm: DA
ctip-options:
- 1

restrict-zone: false
guard-rails: 0
reserve-settings: {
  "column": "freelunch_prob", 
  "thresholds": "percentile:50", 
  "lower_disadvantaged": true ,  
  "reserve_fraction": [0.5, 0.5]
  }
non_designation_boost: 128
soft_reserve_boost: 64

policies:
- Con1

priority-weights:
  ctip: 8
  sibling: 16
  zone: 4
  language-programs:
    lp-sibling: 16
    lp: 8
    sibling: 4
    ctip: 2

  
sibling-access: true
designate: true
zone-building-blocks: 'attendance_area'
ties-options:
- MTB
