data:
  scenario: assignment-generated-zones-2324
  overrides: {}
iterations:
  end: 25
  start: 0
paths:
  assignment-folder: /soalnas/share/data/school_choice/local_runs/8-19-real-acc-fr3/assignments
random-seed: 2023
export-aggregate-metrics: true
export-local-metrics: true

r1-only: true
rounds-merged-options:
- 0
save-assignment: true
subconfigs:
- small_zones+no_reserves
- small_zones+reserves
- small_zones+reserves_05frl
- small_zones+reserves_06frl
- medium_zones+no_reserves
- medium_zones+reserves
- medium_zones+reserves_05frl
- medium_zones+reserves_06frl
- distance_05_1_2+reserves
- distance_05_1_2+reserves_05frl
- distance_05_1_2+reserves_06frl
- status_quo
- status_quo_3
- status_quo_4
- status_quo+reserves
- status_quo+reserves_05frl
- status_quo+reserves_06frl
- distance_05_1_2+reserves_05frl_#3
- distance_05_1_2+reserves_05frl_#4
utility-model:
  designate-lp-for-all: false
  enable: false
  list-length: 0.8*round(real_length)
output_dir: /soalnas/share/data/school_choice/local_runs/8-19-real-acc-fr3/
