data:
  scenario: assignment-zone-only-2324
  overrides: {}
iterations:
  end: 25
  start: 0
paths:
  assignment-folder: /soalnas/share/data/school_choice/local_runs/8-19-real-acc-fr4/assignments
random-seed: 2023
export-aggregate-metrics: true
export-local-metrics: true
reuse_assignments: true

r1-only: true
rounds-merged-options:
- 0
save-assignment: true
subconfigs:
- small_zones+no_reserves
utility-model:
  designate-lp-for-all: false
  enable: false
  list-length: 0.8*round(real_length)
output_dir: /soalnas/share/data/school_choice/local_runs/8-19-real-acc-fr4/
