base_dir: "<STUDENT_ASSIGNMENT_PATH>/local-data/local-runs/status_quo_runs/"
output_dir: "metrics/status_quo_trends_real"

# Metrics that produce a single value per simulation
# Optional: Manually specify runs to analyze.
# If this is set, 'base_dir' discovery is ignored.
runs:
  - label: "2014-2015"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_1415_filtered.csv"
    year: 14
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_1415.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_1415_filtered.csv"
  - label: "2015-2016"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_1516_filtered.csv"
    year: 15
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_1516.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_1516_filtered.csv"
  - label: "2016-2017"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_1617_filtered.csv"
    year: 16
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_1617.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_1617_filtered.csv"
  - label: "2017-2018"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_1718_filtered.csv"
    year: 17
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_1718.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_1718_filtered.csv"
  - label: "2018-2019"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_1819_filtered.csv"
    year: 18
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_1819.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_1819_filtered.csv"
  - label: "2019-2020"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_1920_filtered.csv"
    year: 19
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_1920.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_1920_filtered.csv"
  - label: "2020-2021"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_2021_filtered.csv"
    year: 20
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_2021.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_2021_filtered.csv"
  - label: "2021-2022"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_2122_filtered.csv"
    year: 21
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_2122.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_2122_filtered.csv"
  - label: "2022-2023"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_2223_filtered.csv"
    year: 22
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_2223.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_2223_filtered.csv"
  - label: "2023-2024"
    run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_2324_filtered.csv"
    year: 23
    program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_2324.csv"
    student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_2324_filtered.csv"
  # - label: "2024-2025"
  #   run_csv: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/assignment_2425_filtered.csv"
  #   year: 24
  #   program_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/program_filter/programs_without_specialprogs_2425.csv"
  #   student_data: "<STUDENT_ASSIGNMENT_PATH>/local-data/student_filter/student_2425_filtered.csv"
  
    

single_metrics:
  - "Unassigned"
  - "#Unassigned"
  - "Avg. Distance"
  - "Median Distance"
  - "% assigned within 0.5mi"
  - "% assigned beyond 3mi"
  - "Capacity"
  - "Assigned students"
  - "Students"
  - "Not assigned"
  - "Designated"
  - "Empty Seats"
  - "# GE Empty Seats"
  - "# GE Over Assigned Seats"
  - "Assigned to 1st choice"
  - "Assigned top-3 choice"
  - "# high-poverty schools"
  - "# students in high-poverty schools"
  - "# AALPI students in high-poverty schools"
  - "# of students from high-poverty area"
  - "Total AALPI students"
  - "Total AALPI assigned students"
  - "Total Designated"
  - "Not designated"
  - "#GE programs that have more than 0% and less than 10% of their capacity as African American or Pacific Islander students"
  - "#GE programs that have exactly 0 African American or Pacific Islander students"
  - "#GE programs that have 1-4 African American or Pacific Islander students"
  - "#Schools above +10% district FRL"
  - "Schools above +10% district FRL"
  - "#Students in schools above +10% district FRL"
  - "#Schools above +15% district FRL"
  - "Schools above +15% district FRL"
  - "#Students in schools above +15% district FRL"
  - "#Schools below -10% district FRL"
  - "Schools below -10% district FRL"
  - "#Students in schools below -10% district FRL"
  - "#Schools below -15% district FRL"
  - "Schools below -15% district FRL"
  - "#Students in schools below -15% district FRL"
  - "AALPI in school with +10% FRL"
  - "AALPI in school with +15% FRL"
  - "AALPI in school with -10% FRL"
  - "AALPI in school with -15% FRL"
  - "#GE programs above +10% district FRL"
  - "Proportion of GE programs above +10% district FRL"
  - "#GE programs above +15% district FRL"
  - "Proportion of GE programs above +15% district FRL"
  - "#GE programs below -10% district FRL"
  - "Proportion of GE programs below -10% district FRL"
  - "#GE programs below -15% district FRL"
  - "Proportion of GE programs below -15% district FRL"
  - "AALPI in GE programs with +10% FRL"
  - "AALPI in GE programs with +15% FRL"
  - "AALPI in GE programs with -10% FRL"
  - "AALPI in GE programs with -15% FRL"
  - "AALPI in designated"
  - "#Schools with +10% High Income (95292)"
  - "Prop schools with +10% High Income (95292)"
  - "#Schools with +15% High Income (95292)"
  - "Prop schools with +15% High Income (95292)"
  - "#Schools with -10% High Income (95292)"
  - "Prop schools with -10% High Income (95292)"
  - "#Schools with -15% High Income (95292)"
  - "Prop schools with -15% High Income (95292)"
  - "Prop AALPI in +10% High Income Schools (95292)"
  - "Prop AALPI in +15% High Income Schools (95292)"
  - "Prop AALPI in -10% High Income Schools (95292)"
  - "Prop AALPI in -15% High Income Schools (95292)"
  - "Avg Prop AALPI in +10% High Income Schools (95292)"
  - "Avg Prop AALPI in +15% High Income Schools (95292)"
  - "Avg Prop AALPI in -10% High Income Schools (95292)"
  - "Avg Prop AALPI in -15% High Income Schools (95292)"
  - "Prop AALPI in -10% Low Income Schools (95292)"
  - "Prop AALPI in -15% Low Income Schools (95292)"
  - "Avg Prop FRL in +10% High Income Schools (95292)"
  - "Avg Prop FRL in +15% High Income Schools (95292)"
  - "Dissimilarity (High FRL)"
  # Exposure metrics (difference between groups)
  - "Black/White exposure to AALPI"
  - "Black/White exposure to poverty"
  - "Black/White exposure to low FRL"
  - "Hispanic/White exposure to AALPI"
  - "Hispanic/White exposure to poverty"
  - "Hispanic/White exposure to low FRL"
  # Absolute exposure metrics (no difference)
  - "AALPI exposure to AALPI"
  - "AALPI exposure to high FRL"
  - "AALPI exposure to low FRL"
  - "White exposure to AALPI"
  - "White exposure to high FRL"
  - "White exposure to low FRL"
  - "Black exposure to AALPI"
  - "Black exposure to high FRL"
  - "Black exposure to low FRL"
  - "Hispanic exposure to AALPI"
  - "Hispanic exposure to high FRL"
  - "Hispanic exposure to low FRL"
  - "High FRL exposure to AALPI"
  - "High FRL exposure to high FRL"
  - "High FRL exposure to low FRL"
  - "Low FRL exposure to AALPI"
  - "Low FRL exposure to high FRL"
  - "Low FRL exposure to low FRL"

# Metrics with subgroups (e.g. by Ethnicity)
# The script will look for keys matching "Pattern ({group})" and plot all found groups
group_metrics:
  - "{group} exposure to high FRL"
  - "{group} exposure to FRL prob"
  - "{group} in school with +10% FRL"
  - "{group} in school with +15% FRL"
  - "Prop Top 1 choice ({group})"
  - "Prop Top 2 choice ({group})"
  - "Prop Top 3 choice ({group})"
  - "Nb assigned students ({group}) to LP program"
  - "Nb assigned students ({group}) to immersion program"
  - "Nb assigned students ({group}) to non-immersion program"
  - "Nb assigned students ({group}) to GE program"
  - "Nb designated students ({group}) to LP program"
  - "Dissimilarity ({group})"
  - "Number of assigned students ({group})"
  - "Distance Median ({group})"
  - "Nb assigned students ({group}) to CE" # Assuming CE is in self.ce_se
  - "Nb assigned students ({group}) to SE" # Assuming SE is in self.ce_se
  - "Nb designated students ({group}) to CE"
  - "Nb designated students ({group}) to SE"
  - "Distance Av ({group})"
  - "Distance Median ({group})"
  - "Distance < 0.5 ({group})"
  - "Distance < 1 ({group})"
  - "Distance > 3 ({group})"
  - "Dissimilarity ({group})"
