data:
  scenario: assignment-generated-zones-2324
  overrides:
    filters:
      assignment:
        special_programs: exclude_any_special
iterations:
  end: 25
  start: 0
paths:
  assignment-folder: /soalnas/share/data/school_choice/local_runs/dummy/
# should be replaced 

random-seed: 2023
export-aggregate-metrics: true
export-local-metrics: true
reuse_assignments: false

r1-only: true
rounds-merged-options:
- 0
save-assignment: true
subconfigs:
- zone_apples
utility-model:
  designate-lp-for-all: false
  enable: true
  list-length: 0.8*round(real_length)
