data:
  scenario: legacy
  overrides:
    sources:
      assignment.students:
        path: <STUDENT_ASSIGNMENT_PATH>/local-data/pipeline_runs/train_${train_year}_test_${test_year}/r1_students_filtered.csv
        classification: restricted
      assignment.programs:
        path: /soalnas/share/data/school_choice/Data/Cleaned/programs_${year}.csv
        classification: internal
      assignment.schools:
        path: /soalnas/share/data/school_choice/Data/Cleaned/schools_rehauled_${year}.csv
        classification: internal
      assignment.estimate:
        path: <SFUSD_CHOICE_PATH>/pipeline_output/train_${train_year}_test_${test_year}/estimates_${train_year}_${test_year}.csv
        classification: restricted
      assignment.school_coordinates:
        path: /soalnas/share/data/school_choice/Data/Cleaned/schools_rehauled_${year}.csv
        classification: internal
      assignment.zones:
        10zone:
          path: /soalnas/share/data/school_choice/simulation-files/zones/10-zone-11_BG.csv
          classification: public
        13zone:
          path: /soalnas/share/data/school_choice/simulation-files/zones/13-zone-7_BG.csv
          classification: public
        18zone_1:
          path: /soalnas/share/data/school_choice/simulation-files/zones/18-zone-1_1_BG.csv
          classification: public
        18zone_2:
          path: /soalnas/share/data/school_choice/simulation-files/zones/18-zone-1_2_BG.csv
          classification: public
        59zone:
          path: /soalnas/share/data/school_choice/simulation-files/zones/59-zone-1_B.csv
          classification: public
        6zone-1:
          path: /soalnas/share/data/school_choice/simulation-files/zones/6-zone-1_BG.csv
          classification: public
        Con1:
          path: /soalnas/share/data/school_choice/simulation-files/zones/concept1zones.csv
          classification: public
    filters:
      assignment:
        year: "${year}"
        grades: [KG]
        student_population: applicant
        rounds:
        - 1
        special_programs: exclude_any_special
        capacity_profile: default
        include_mission_bay: false
paths:
  assignment-folder: <STUDENT_ASSIGNMENT_PATH>/local-data/pipeline_runs/train_${train_year}_test_${test_year}/
utility-model:
  enable: true
  designate-lp-for-all: false
  list-length: 0.8*round(real_length)
  save-path: <STUDENT_ASSIGNMENT_PATH>/local-data/pipeline_runs/train_${train_year}_test_${test_year}/utility_matrix.csv
subconfigs:
- status_quo
r1-only: true
random-seed: 2023
iterations:
  start: 0
  end: 10
save-assignment: true
rounds-merged-options:
- 0
