name: iterative-choice
mode: run

optimization_defaults:
  levels: ['Block_1']     # use ['BlockGroup_0'] for full fine-grained test
  strategy: 'iterative_choice'
  linearization_level: 2

  frl_dev: 0.15
  racial_dev: -1
  overage: 0.15
  shortage: 0.15
  max_distance: 4

  solve_time_limits: [300]
  hints: gerry_chain
  workers: 8

  max_iterations: 25
  tolerance: 0

  choice_model: 'mnl'
  choice_utility_scale: 100.0

sweep:
  centroids_type: ['6-zone-3',  '8-zone-24', '10-zone-3',  '13-zone-6']
  seed: [42, 14, 33]
  solver: ['cp_bool', 'mip']

tasks:
  - choice_model_method: 'logsum'
  - choice_model_method: 'max'
  - strategy: 'single'


execution:
  output_dir: '/share/data/school_choice/local_runs/iterative_choice_updated_5'
  capacity: 40
  max_workers: 5
  max_tasks_per_worker: 5
  skip_existing: true
  rerun_failed: true
  sequential: false

metrics:
  strict: true
  compute_stage_metrics: false
  summary_csv: 'summary.csv'
  stages_csv: 'stages.csv'

matching:
  enabled: true
  configs:
    - name: sd
      config: Zone_Generation/benchmark/matching/sd.yaml
    - name: no_reserves
      config: Zone_Generation/benchmark/matching/zones+no_reserves.yaml
    - name: soft_reserves
      config: Zone_Generation/benchmark/matching/zones+soft_reserves_06frl.yaml
    - name: hard_reserves
      config: Zone_Generation/benchmark/matching/zones+hard_reserves_06frl.yaml
  compute_stage_assignments: true

choice_metrics:
  enabled: true
  compute_stage_metrics: true
